env:
  browser: true
  es6: true
  jquery: true
parserOptions:
  sourceType: module
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
