@extends:
    '@parent'

form:
    fields:
        content:

            fields:
                custom_file:
                  name: myfile
                  type: file
                  label: A Label
                  destination: 'user/plugins/my-plugin/assets'
                  multiple: true
                  autofocus: false
                  accept:
                    - image/*
