title: Default Page
'@extends':
    type: default
    context: blueprints://pages

form:
    fields:
        tabs:
            fields:
                content:
                    fields:
                        header.media_order:
                            unset@: true

                        pageHeader:
                            type: section
                            title: Page Images
                            underline: true
                            ordering@: 999

                            import@:
                                type: partials/headerimages
                                context: blueprints://
