title: Default Page
'@extends':
    type: default
    context: blueprints://pages

form:
    fields:
        tabs:
            fields:
                content:
                    fields:
                        pageHeader:
                            type: section
                            ordering@: 999

                            import@:
                                type: partials/headerimages
                                context: blueprints://

                options:
                    fields:
                        taxonomies:
                            unset@: true